# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kate Avery
# tagline:          'A Jekyll theme'
description:      'Computer scientist and ML researcher. <br />Currently working on a <br /><a href="https://groups.cs.umass.edu/kdl/" target="_blank">PhD @ UMass Amherst</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kate Avery'
  url:            https://twitter.com/mdo

plugins:          [jekyll-paginate]
gems:             [jekyll-gist]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
